export const ENV = {
  API_BASE_URL: process.env.EXPO_PUBLIC_API_BASE_URL!,
  GOOGLE_MAPS_API_KEY: process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY!,
  IMAGE_BASE_URL: process.env.EXPO_PUBLIC_IMAGE_BASE_URL!,
  MERCHANT_NAME: process.env.EXPO_PUBLIC_MERCHANT_NAME!,
  STRIPE_PUBLISHABLE_KEY: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY!,
  URL_SCHEME: process.env.EXPO_PUBLIC_URL_SCHEME!,
};
